import loginRouter from './login';
import { Router } from 'express';
import employeeRouter from './employee';
import categoryRouter from './category';
import mealRouter from './meal';
const adminRouter = Router();
adminRouter.use(loginRouter);
adminRouter.use(employeeRouter);
adminRouter.use('/category', categoryRouter);
adminRouter.use('/setmeal', mealRouter);
export default adminRouter;
